name: primerxamen1_miguelc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
    dio: ^5.4.0
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  provider: ^6.1.1
  core: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true